# Description
# ===========
# This playbook create a Windows Server VM in Azure with ports open for ssh, http(s), rdp and winrm

---
- name : Deploy Windows on Azure
  hosts: localhost 
  gather_facts: False
  vars: 
    vm_name: MSW2016
    resource_group: ansibletower
    location: australiacentral
  tasks:
    - block:
      - name: Azure Create virtual network
        azure_rm_virtualnetwork:
          name: "{{ vm_name }}"
          state: absent
          resource_group: "{{ resource_group }}"

      - name: Azure Add subnet
        azure_rm_subnet:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}"
          state: absent


      - name: Azure Create Network Security Group that allows SSH and HTTP Ports
        azure_rm_securitygroup:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}"
          state: absent

      # Create windows
      - name: Create windows public IP address
        azure_rm_publicipaddress:
          resource_group: "{{ resource_group }}"
          name: mswin
          state: absent

      - name: Create windows virtual network inteface card
        azure_rm_networkinterface:
          resource_group: "{{ resource_group }}"
          name: mswin
          state: absent

      - name: Azure Create windows VM
        azure_rm_virtualmachine:
          resource_group: "{{ resource_group }}"
          name: mswin
          state: absent