# Description
# ===========
# This playbook create an Azure VM with public IP, and open 22 port for SSH
# This playbook creates an EC2 VM with public IP, and assign to security group with port 22 open.

---
- name : Simple playbook
  hosts: localhost 
  gather_facts: False
  vars:
    azurewebservers:
      - { vmname: 'webserver1', nic: 'webserver1' }
      - { vmname: 'webserver2', nic: 'webserver2' }
  tasks:
    - block:
      - name: Azure Create virtual network
        azure_rm_virtualnetwork:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}"
          address_prefixes: "10.0.0.0/16"
      - name: Azure Add subnet
        azure_rm_subnet:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}"
          address_prefix: "10.0.1.0/24"
          virtual_network: "{{ vm_name }}"
      - name: Azure Create Network Security Group that allows SSH
        azure_rm_securitygroup:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}"
          rules:
            - name: SSH
              protocol: Tcp
              destination_port_range: 22
              access: Allow
              priority: 1001
              direction: Inbound
            - name: HTTP
              protocol: Tcp
              destination_port_range: 80
              access: Allow
              priority: 1002
              direction: Inbound
            - name: HTTPS
              protocol: Tcp
              destination_port_range: 443
              access: Allow
              priority: 1003
              direction: Inbound
            - name: LB
              protocol: Tcp
              destination_port_range: 8888
              access: Allow
              priority: 1004
              direction: Inbound

      # Create windows
      - name: Create windows public IP address
        azure_rm_publicipaddress:
          resource_group: "{{ resource_group }}"
          allocation_method: Static
          name: windows

      - name: Create windows virtual network inteface card
        azure_rm_networkinterface:
          resource_group: "{{ resource_group }}"
          name: windows
          virtual_network: "{{ vm_name }}"
          subnet: "{{ vm_name }}"
          public_ip_name: windows
          security_group: "{{ vm_name }}"

      - name: Aure Create windows VM
        azure_rm_virtualmachine:
          resource_group: "{{ resource_group }}"
          name: windows
          vm_size: Standard_A0
          admin_username: ec2-user 
          admin_password: Password@123
          tags:
            tag_ansible_group : windows
            network_interfaces: windows
          image:
            offer: WindowsServer
            publisher: MicrosoftWindowsServer 
            sku: '2016-Datacenter'
            version: latest
        register: output	