---
- name: Install Active Directory
  hosts: mswin
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  gather_facts: false
  roles:
    - win_ad_install