---
- name: Install SSH Server
  hosts: mswin
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
  gather_facts: false
  vars_files:
    - win_ssh_var.yml
  roles:
    - win_package_install
    - win_service_config
    - win_firewall
